apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrapper-api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrapper-api-v2
  template:
    metadata:
      labels:
        app: wrapper-api-v2
    spec:
      containers:
        - name: wrapper-api-v2
          image: nishantdoshi9/nishrepo:wrapperapiv1
          ports:
            - containerPort: 8090
          env:
            - name: PORT
              value: "8090"
---
apiVersion: v1
kind: Service
metadata:
  name: wrapper-api-v2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: wrapper-api-v2